### ISSUE TITLE
۱.  چه کسانی میتواند ریکت رو شروع کند

### ISSUE THREAD

**Issue by echoWebNerds** [echoWebNerds/articles#11]

**Comment by mohmmadView** [comment]
هترین زمان برای یادگیری React زمانی است که از اصول اولیه توسعه وب مانند HTML، CSS و JavaScript مطلع باشید. با این دانسته ها، می توانید شروع به یادگیری React کنید و به سرعت یک وب سایت تعاملی و جذاب ایجاد کنید.

React یک چارچوب جاوا اسکریپت محبوب است که برای ساخت رابط های کاربری تعاملی استفاده می شود. این یک چارچوب بسیار قدرتمند و انعطاف پذیر است که می توان از آن برای ساخت طیف گسترده ای از برنامه های وب استفاده کرد.

اگر علاقه مند به یادگیری React هستید، منابع زیادی در دسترس هستند. می توانید کتاب ها، دوره ها و آموزش های ویدئویی زیادی را پیدا کنید که به شما کمک می کنند یاد بگیرید چگونه از React استفاده کنید.

در اینجا چند نکته برای شروع یادگیری React آورده شده است:

با اصول اولیه توسعه وب مانند HTML، CSS و JavaScript آشنا شوید.
یک دوره React را انتخاب کنید و شروع به یادگیری نحوه استفاده از React کنید.
پروژه های React را ایجاد کنید تا مهارت های خود را تمرین کنید.
در یک جامعه React شرکت کنید و با سایر توسعه دهندگان تعامل داشته باشید.
با پیروی از این نکات، می توانید شروع به یادگیری React کنید و به سرعت یک وب سایت تعاملی و جذاب ایجاد کنید.

**Comment by mohmmadView** [comment]
قبل از شروع به یادگیری React، مطمئن شوید که شما با مفاهیم اولیه زیر آشنا هستید:

    HTML، CSS و JavaScript: React یک کتابخانه JavaScript برای توسعه رابط‌های کاربری است، بنابراین آشنایی با HTML برای ساختاردهی و محتوا، CSS برای ظاهر و ظاهری زیبا و JavaScript برای برنامه‌نویسی و انجام عملیات تعاملی اساسی است.

    ES6+ (ECMAScript 2015 به بالا): ES6 یا ورژن‌های بالاتر از ECMAScript مجموعه‌ای از بهبودهای جدید در JavaScript اضافه کردند که برای کدنویسی React بهتر و کارآمدتر می‌باشد. از ویژگی‌های ES6 مانند کلاس‌ها، فرمت‌بندی اشیاء، Arrow functions، و Const و Let برای متغیرها باید آگاه باشید.

    مفاهیم DOM: React با Virtual DOM کار می‌کند، اما درک مفاهیم اصلی DOM (Document Object Model) بسیار کاربردی است. این شامل مفاهیم مربوط به اندازه‌گیری، انتخاب و تغییر عناصر HTML در صفحه می‌شود.

    بستر کار با Node.js: React برای اجرای وب سرور نیاز به Node.js دارد. اگر قصد دارید برنامه‌های React خود را توسعه و اجرا کنید، باید با نصب و کانفیگ کردن Node.js و npm (Node Package Manager) آشنا باشید.

    نصب و راه‌اندازی محیط توسعه: برای شروع کار با React، باید محیط توسعه مانند VSCode یا WebStorm را راه‌اندازی کنید. همچنین برخی از ابزارها مانند Create React App یا Next.js نیز برای تسهیل در توسعه React استفاده می‌شوند.

هرچند که این پیش‌نیازها می‌توانند متفاوت باشند، اما این موارد مبتنی بر دانش‌های اولیه و کاربردی در توسعه وب و JavaScript هستند. با مطالعه و مرور این مفاهیم، شما به راحتی می‌توانید به یادگیری React پرداخته و برنامه‌های کاربردی پویا و مدرن بسازید.

**Comment by mohmmadView** [comment]
### قبل از شروع به یادگیری React، مطمئن شوید که شما با مفاهیم اولیه زیر آشنا هستید:


</h3>  داشته باشیم     Html   و css و   javascribt   برای اینکه بتونیم ریکت رو شروع کنیم بهتر هست اشنای کامل  رو با      <h3>                                   

   2. ES6+ (ECMAScript 2015 به بالا): ES6 یا ورژن‌های بالاتر از ECMAScript مجموعه‌ای از بهبودهای جدید در JavaScript اضافه کردند که برای کدنویسی React بهتر و کارآمدتر می‌باشد. از ویژگی‌های ES6 مانند کلاس‌ها، فرمت‌بندی اشیاء، Arrow functions، و Const و Let برای متغیرها باید آگاه باشید.

3. مفاهیم DOM: React با Virtual DOM کار می‌کند، اما درک مفاهیم اصلی DOM (Document Object Model) بسیار کاربردی است. این شامل مفاهیم مربوط به اندازه‌گیری، انتخاب و تغییر عناصر HTML در صفحه می‌شود.

4. بستر کار با Node.js: React برای اجرای وب سرور نیاز به Node.js دارد. اگر قصد دارید برنامه‌های React خود را توسعه و اجرا کنید، باید با نصب و کانفیگ کردن Node.js و npm (Node Package Manager) آشنا باشید.

5. نصب و راه‌اندازی محیط توسعه: برای شروع کار با React، باید محیط توسعه مانند VSCode یا WebStorm را راه‌اندازی کنید. همچنین برخی از ابزارها مانند Create React App یا Next.js نیز برای تسهیل در توسعه React استفاده می‌شوند.

هرچند که این پیش‌نیازها می‌توانند متفاوت باشند، اما این موارد مبتنی بر دانش‌های اولیه و کاربردی در توسعه وب و JavaScript هستند. با مطالعه و مرور این مفاهیم، شما به راحتی می‌توانید به یادگیری React پرداخته و برنامه‌های کاربردی پویا و مدرن بسازید.
