### ISSUE TITLE
پیدا کردن شغار منحصر به  فرد برای کانال

### ISSUE THREAD

**Issue by Zarpoosh** [echoWebNerds/articles#23]
اینا نمونه هایی شعار یا تکیه کلام مربوط به حوزه برنامه نویسی هستن  که میتونه مثل امضا و اثرانگشت رو پست ها اموزش ها و....قرار بگیره. 

"Think big, code big."
"Failure is part of learning. Don't be afraid of it."
"If you can imagine it, you can build it."
"Never give up. There is always a solution."
"Coding changes the world. Let's be a part of it."

**Comment by mohmmadView** [comment]
### Failure is part of learning. Don't be afraid of it."
مینو عالیه شعار نظر من   میتونیم    برای هر پست شهر جدید
هرچی زودتر پست اول بدهیم بیرون
