### ISSUE TITLE
نکاتی در ارتباط  با توسعه پروفایل لینکدین

### ISSUE THREAD

**Issue by Zarpoosh** [echoWebNerds/articles#8]
۱-عکس پروفایل مرتبط،منحصر به فرد،شیک و به یاد ماندنی
۲بنر مرتبط ،جذاب و با مفهوم
۳-هدلاین: شغلمون چیه ،در حد چند کلمه یا یه جمله
۴-درباره ما: توضیح مفید و مختصر در باره مهارت ها ،تجربه،اهداف،کی هستیم و چیکار میکنیم
۵-تجربه های کاریمون
۶-تحصیلات و مدارک
۷-لیست مهارت های که داریم
۸-کانکشن ها: ایجاد کانکشن با recruiter ها در اولویت هست چون میتونن ارتباط ما رو با کمپانی های خارجی برقرار کنند.در مرحله دوم افراد متخصص و کسانی که در حوزه ما فعالیت دارن.همچنین هنگام ایجاد کانکشن باید رزومه و سابقه افراد رو بررسی کنیم از جمله مهارت و تخصص و پست های که میزارن تا افراد مرتبط با فیلد کاری خودمون رو اضافه کنیم و از افزودن افراد سمی و غیر ضروری خودداری کنیم
۹-هنگام request زدن به افراد برای دعوت باید یه متن مناسب و جذاب بنویسیم.که مخاطب رو قانع کنه و از پروفایل یا گروه ما دیدن کنه.

**Comment by mohmmadView** [comment]
خوب نکات عالی هستن  ولی باید نکات بیشتری به این لیست اضافه بشه
